language: python
python:
    - 2.7
    - 3.3
virtualenv:
    # This allows installing PyQt using apt-get and being able to import it.
    system_site_packages: true

before_install:
    # Install PyQt4 for running the UI tests.
    source .travis_before_install
install:
    - pip install pygments
    - sudo apt-get install python-numpy
    - sudo apt-get install python3-numpy
    # Test against the current master of traits
    - pip install git+http://github.com/enthought/traits.git#egg=traits
    # Test against the current python3 branch of pyface
    - pip install git+http://github.com/pradyun/pyface.git@python3#egg=pyface
    - python setup.py develop

script:
    - python setup.py nosetests
    - python setup.py nosetests
