language: python
python:
  - 2.7
  - 3.3
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
before_install:
  # On Python 2.7 we install PyQt4 and run the UI tests.
  - source .travis_before_install
install:
  # nose is already installed
  - pip install pygments
  - sudo apt-get install python-numpy
  - sudo apt-get install python3-numpy
  # Test against the current master of traits, traitsui and enable
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - python setup.py develop
script:
  - nosetests traitsui.tests
  - nosetests traitsui.qt4.tests
notifications:
  email:
    - pradyunsg@enthought.com
