language: generic
sudo: false
env:
  global:
    - INSTALL_EDM_VERSION=1.5.2
      PYTHONUNBUFFERED="1"
matrix:
  include:
    - env: RUNTIME=2.7 TOOLKITS="null pyqt pyside"
    - env: RUNTIME=3.5 TOOLKITS="null pyqt"
    - env: RUNTIME=3.5 TOOLKITS="pyqt5"
    - env: RUNTIME=2.7 TOOLKITS="wx"
    - os: osx
      env: RUNTIME=3.5 TOOLKITS="null pyqt"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="null pyside"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="pyqt wx"
  allow_failures:
    - env: RUNTIME=2.7 TOOLKITS="wx"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="pyqt wx"
  fast_finish: true
branches:
  only:
    - master
cache:
  directories:
    - "~/.cache"
before_install:
  - mkdir -p "${HOME}/.cache/download"
  - export DISPLAY=:99.0
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./install-edm-linux.sh; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ./install-edm-osx.sh; fi
  - edm install -y wheel click
install:
  - for toolkit in ${TOOLKITS}; do edm run -- python -m tasks install --runtime=${RUNTIME} --toolkit=${toolkit}; done
script:
  - for toolkit in ${TOOLKITS}; do edm run -- python -m tasks test --runtime=${RUNTIME} --toolkit=${toolkit}; done
after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
