language: python
python:
    - 2.7
    - 3.3
virtualenv:
    # This allows installing PyQt using apt-get and being able to import it.
    system_site_packages: true
before_install:
    # Install PyQt4 for running the UI tests.
    - source .travis_before_install
install:
    - pip install pygments
    - sudo apt-get install python-numpy
    - sudo apt-get install python3-numpy
    # Test against the current master of traits
    - pip install git+http://github.com/enthought/traits.git#egg=traits
    # Test against the current python3 of pyface
    - pip install git+http://github.com/pradyun/pyface.git@python3#egg=pyface
    - {envpython} setup.py develop
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then {envpython} setup.py build; fi
before_script:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then cd build; fi
script:
    - nosetests traitsui.tests
    - nosetests traitsui.qt4.tests
after_script:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then cd ..; fi

