language: python
python:
    - 2.7
    - 3.3
before_install:
    # Set up for UI tests.
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - export ETS_TOOLKIT=qt4

install:
    # Basic dependencies
    - pip install numpy
    - pip install pyside
    - pip install pygments

    # Test against the current master of traits
    - pip install git+http://github.com/enthought/traits.git#egg=traits
    # Test against the current python3 branch of pyface
    - pip install git+http://github.com/pradyun/pyface.git@python3#egg=pyface
    - python setup.py develop

script:
    - python setup.py nosetests
