language: python
sudo: false
python:
  - 2.7_with_system_site_packages
env:
  - RUNTIME=2.7 TOOLKIT=null
  - RUNTIME=2.7 TOOLKIT=pyqt
  - RUNTIME=2.7 TOOLKIT=pyside
  - RUNTIME=2.7 TOOLKIT=wxpython
  - RUNTIME=3.5 TOOLKIT=null
  - RUNTIME=3.5 TOOLKIT=pyqt
cache:
  directories:
    - $HOME/.edm
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://package-data.enthought.com/edm/rh5_x86_64/1.3/edm_1.3.0_linux_x86_64.sh
  - chmod u+x edm_1.3.0_linux_x86_64.sh
  - ./edm_1.3.0_linux_x86_64.sh -b
  - export PATH=~/edm/bin:${PATH}
  - pip install invoke
script:
  - invoke test --runtime=${RUNTIME} --toolkit=${TOOLKIT}
after_success:
  - pip install codecov
  - codecov
