language: python
sudo: false
python:
  - 2.7_with_system_site_packages
env:
  - TOOLKIT=pyqt
  - TOOLKIT=pyside
  - TOOLKIT=null
  - TOOLKIT=wx
  - RUNTIME=2.7
  - RUNTIME=3.5
matrix:
  exclude:
    - RUNTIME=3.5
      TOOLKIT=wx
    - RUNTIME=3.5
      TOOLKIT=pyside
cache:
  directories:
    - $HOME/.edm
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://package-data.enthought.com/edm/rh5_x86_64/1.3/edm_1.3.0_linux_x86_64.sh
  - chmod u+x edm_1.3.0_linux_x86_64.sh
  - ./edm_1.3.0_linux_x86_64.sh
  - pip install invoke
script:
  - invoke test --runtime={RUNTIME} -- toolkit={TOOLKIT}
after_success:
  - pip install codecov
  - codecov
