language: python
sudo: false
env:
  - RUNTIME=2.7 TOOLKIT=null
  - RUNTIME=2.7 TOOLKIT=pyqt
  - RUNTIME=2.7 TOOLKIT=pyside
  - RUNTIME=2.7 TOOLKIT=wx
  - RUNTIME=3.5 TOOLKIT=null
  - RUNTIME=3.5 TOOLKIT=pyqt
matrix:
  include:
    - python: 2.7
    - langauge: generic
      os: osx
  allow_failures:
    - env: RUNTIME=2.7 TOOLKIT=wx
  fast_finish: true
cache:
  directories:
    - $HOME/.edm
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ ${TRAVIS_OS_NAME} == "osx"]]; then wget https://package-data.enthought.com/edm/osx_x86_64/1.3/edm_1.3.0.pkg; else wget https://package-data.enthought.com/edm/rh5_x86_64/1.3/edm_1.3.0_linux_x86_64.sh; fi
  - if [[ ${TRAVIS_OS_NAME} == "osx"]]; then sudo installer -pkg edm_1.3.0.pkg -target /; else ./edm_1.3.0_linux_x86_64.sh -b -p ~; fi
  - export PATH="~/bin:${PATH}"
  - edm install invoke
install:
  - edm run -- invoke install --runtime=${RUNTIME} --toolkit=${TOOLKIT}
script:
  - edm run -- invoke test --runtime=${RUNTIME} --toolkit=${TOOLKIT}
  - edm run -- invoke cleanup --runtime=${RUNTIME} --toolkit=${TOOLKIT}
after_success:
  - pip install codecov
  - codecov
