build: false
shallow_clone: true
skip_branch_with_pr: true
environment:

  global:
    PYTHONUNBUFFERED: "1"
    INSTALL_EDM_VERSION: "1.7.1"

  matrix:

    - RUNTIME: '2.7'
      TOOLKITS: "null pyqt pyside"
    - RUNTIME: '3.5'
      TOOLKITS: "null pyqt pyqt5"
    - RUNTIME: '2.7'
      TOOLKITS: "wx"

matrix:
  fast_finish: True
  allow_failures:
    - RUNTIME: '2.7'
      TOOLKITS: "wx"

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.cache -> appveyor-clean-cache.txt
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-clean-cache.txt

init:
  - ps: $Env:path = "C:/Enthought/edm;" + $Env:path
  - ps: md C:/Users/appveyor/.cache -Force
  - ps: $WarningPreference = 'SilentlyContinue'
  - ps: $ErrorActionPreference = "SilentlyContinue"

install:
  - install-edm-windows.cmd
  - edm install -y wheel click coverage
  - ps: ForEach ($t in $Env:TOOLKITS.split(" ")) { edm run -- python -m tasks install --runtime=$Env:RUNTIME --toolkit=$t }
test_script:
  - ps: ForEach ($t in $Env:TOOLKITS.split(" ")) { edm run -- python -m tasks test --runtime=$Env:RUNTIME --toolkit=$t }
on_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
