build: false
shallow_clone: true

environment:

  global:
    PYTHONUNBUFFERED: "1"
    INSTALL_EDM_VERSION: "1.6.1"

  matrix:

    - RUNTIME: '2.7'
      TOOLKITS: "null pyqt pyside"
    - RUNTIME: '3.5'
      TOOLKITS: "null pyqt"
    - RUNTIME: '3.5'
      TOOLKITS: "pyqt5"
    - RUNTIME: '2.7'
      TOOLKITS: "wx"

matrix:
  allow_failures:
    - RUNTIME: '2.7'
      TOOLKITS: "wx"

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.cache -> appveyor-clean-cache.txt
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-clean-cache.txt

init:
  - ps: $Env:path = "C:/Enthought/edm;" + $Env:path
  - ps: md C:/Users/appveyor/.cache -Force

install:
  - install-edm-windows.cmd
  - edm install -y wheel click
  - ps: ForEach ($t in $Env:TOOLKITS.split(" ")) {edm run -- python -m tasks install --runtime=$Env:RUNTIME --toolkit=$t}
test_script:
  - ps: ForEach ($t in $Env:TOOLKITS.split(" ")) {edm run -- python -m tasks test --runtime=$Env:RUNTIME --toolkit=$t}
on_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
