build: false
shallow_clone: true

environment:

  global:
    PYTHONUNBUFFERED: "1"
    INSTALL_EDM_VERSION: "1.6.1"

  matrix:

    - RUNTIME: '2.7'
      TOOLKITS: "null pyqt pyside"
    - RUNTIME: '3.5'
      TOOLKITS: "null pyqt"
    - RUNTIME: '3.5'
      TOOLKITS: "pyqt5"
    - RUNTIME: '2.7'
      TOOLKITS: "wx"

matrix:
  allow_failures:
    - RUNTIME: '2.7'
      TOOLKITS: "wx"

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.cache -> appveyor-clean-cache.txt
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-clean-cache.txt

init:
  - ps: $Env:path = "C:/Enthought/edm;" + $Env:path
  - ps: md C:/Users/appveyor/.cache -Force

install:
  - cmd: install-edm-windows.cmd
  - ps: edm install wheel click
  - ps: ForEach (toolkit in $env:TOOLKITS) { edm run -- python -m tasks install --runtime=$env:RUNTIME --toolkit=$toolkit}
test_script:
  - ps: ForEach (toolkit in $env:TOOLKITS) { edm run -- python -m tasks test --runtime=$env:RUNTIME --toolkit=$toolkit}
on_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
